watson.id=2d224bd0-54e4-4c09-8752-1dcd066e77f6
watson.apiKey=pHqrUmMmZRQ51ITDoNERUnQRq9XA-FoF8Q5uDH3OpcHq
watson.url=https://api.us-south.assistant.watson.cloud.ibm.com/instances/38ba9f63-662e-49f5-be22-a0ca04ead054
watson.name=Sparkles
watson.version=version;
